README.md
backend/src/main/java/de/grimsi/gameyfin/GameyfinApplication.java
docker/Dockerfile

Shorten startup command

---

backend/pom.xml
backend/src/main/java/de/grimsi/gameyfin/mapper/GameMapper.java
backend/src/main/java/de/grimsi/gameyfin/service/DownloadService.java
backend/src/main/java/de/grimsi/gameyfin/service/LibraryService.java
frontend/pom.xml
pom.xml

Fixes #16 
Corrupted files are now automatically re-downloaded

Fix handling of duplicates

---

backend/pom.xml
backend/src/main/java/de/grimsi/gameyfin/mapper/GameMapper.java
frontend/pom.xml
pom.xml

Fix bug when trying to determine file size for files

Release 1.1.3

---

backend/pom.xml
docker/docker-compose.example-with-multiple-source-folders.yml
frontend/package-lock.json
frontend/package.json
frontend/pom.xml
frontend/src/app/components/footer/footer.component.html
frontend/src/app/components/footer/footer.component.ts
pom.xml

New features:
- Gameyfin version is now displayed in footer (closes #22)

Release 1.2.1

---

backend/pom.xml
backend/src/main/java/de/grimsi/gameyfin/config/FilesystemConfig.java
backend/src/main/java/de/grimsi/gameyfin/service/LibraryService.java
frontend/package-lock.json
frontend/package.json
frontend/pom.xml
pom.xml

Ignore empty folders and hidden files/folders in the library

---

backend/src/main/java/de/grimsi/gameyfin/service/LibraryService.java

Fix error while configuring or scanning a library

---

backend/src/main/java/de/grimsi/gameyfin/util/FilenameUtil.java
backend/src/test/java/de/grimsi/gameyfin/util/FilenameUtilTest.java

I guess it is always good to have more tests, because I apparently forgot to also remove trailing [] noise, which I fixed in this PR too.

Validate some combinations of filename with added suffixes

---

frontend/src/app/app-routing.module.ts

Fix website scroll positions

---

frontend/src/app/components/library-overview/library-overview.component.html
frontend/src/app/components/library-overview/library-overview.component.ts

Fix collapse of expansion panels

---

backend/pom.xml
backend/src/main/java/de/grimsi/gameyfin/config/SecurityConfiguration.java
backend/src/main/java/de/grimsi/gameyfin/entities/Company.java
backend/src/main/java/de/grimsi/gameyfin/entities/DetectedGame.java
backend/src/main/java/de/grimsi/gameyfin/entities/Genre.java
backend/src/main/java/de/grimsi/gameyfin/entities/Keyword.java
backend/src/main/java/de/grimsi/gameyfin/entities/Library.java
backend/src/main/java/de/grimsi/gameyfin/entities/Platform.java
backend/src/main/java/de/grimsi/gameyfin/entities/PlayerPerspective.java
backend/src/main/java/de/grimsi/gameyfin/entities/Theme.java
backend/src/main/java/de/grimsi/gameyfin/entities/UnmappableFile.java
backend/src/main/java/de/grimsi/gameyfin/igdb/IgdbWrapper.java
backend/src/main/java/de/grimsi/gameyfin/service/ImageService.java
backend/src/test/java/de/grimsi/gameyfin/repositories/UnmappableFileRepositoryTest.java
backend/src/test/java/de/grimsi/gameyfin/service/GameServiceTest.java
frontend/package-lock.json
frontend/package.json
pom.xml

This pull request will update Spring Boot from 2to 3.

Update backend to Spring Boot 3

---

backend/src/main/resources/config/gameyfin.yml

Addresses #92 
So, I spent some time gathering data and I put it into the config with some comments. I used the data from the table linked by @CraftyCanine to produce the extensions list, and queried the IGDB api to get the platforms list. I didn't add any new preferred platforms so I might need to go back over the preferred extensions list to remove platforms that won't show up in search results. I also subtracted save and shader files from the extensions list. I'm also not sure if the preferred platforms list is definitive. It might be good to have more platforms available by default.

Add preferred platforms with comments.

---

.github/workflows/build.yml
.github/workflows/docker-build-push.yml
.github/workflows/release.yml
backend/pom.xml
backend/src/main/java/de/grimsi/gameyfin/config/properties/GameyfinProperties.java
backend/src/main/java/de/grimsi/gameyfin/util/FilenameUtil.java
frontend/package-lock.json
frontend/package.json
frontend/pom.xml

Release 1.4.2

---

docker/Dockerfile

Switch Docker base image

---

backend/src/main/java/de/grimsi/gameyfin/service/ImageService.java
backend/src/main/java/de/grimsi/gameyfin/service/LibraryService.java
frontend/package-lock.json
frontend/package.json

Release 1.4.4

---

backend/src/main/resources/config/gameyfin.yml

Fix file extensions in config file

---

app/src/main/frontend/components/administration/SsoManagement.tsx
app/src/main/frontend/views/MainLayout.tsx
app/src/main/kotlin/org/gameyfin/app/config/ConfigEndpoint.kt
app/src/main/kotlin/org/gameyfin/app/core/logging/LogEndpoint.kt
app/src/main/kotlin/org/gameyfin/app/core/plugins/PluginEndpoint.kt
app/src/main/kotlin/org/gameyfin/app/core/security/CustomAuthenticationEntryPoint.kt
app/src/main/kotlin/org/gameyfin/app/core/security/SecurityConfig.kt
app/src/main/kotlin/org/gameyfin/app/core/security/SsoAuthenticationSuccessHandler.kt
app/src/main/kotlin/org/gameyfin/app/games/GameService.kt
app/src/main/kotlin/org/gameyfin/app/libraries/LibraryEndpoint.kt
app/src/main/kotlin/org/gameyfin/app/users/UserEndpoint.kt
app/src/main/kotlin/org/gameyfin/app/users/UserService.kt
app/src/main/kotlin/org/gameyfin/app/users/util/UserDetailsExtensions.kt
app/src/main/resources/application.yml

Fixes:
- No direct login when using SSO
- Reference non-existent user (if SSO auto-registration is turned off)
- SSO redirect issues (#614)

Fix SSO issues

---

app/src/main/frontend/components/general/IconBackgroundPattern.tsx
app/src/main/frontend/routes.tsx
app/src/main/frontend/views/ErrorView.tsx

Implement custom error page

---

.github/actions/docker-build-push/action.yml
docker/Dockerfile.ubuntu
docker/entrypoint.ubuntu.sh

Add image with Ubuntu base

---

app/src/main/frontend/components/general/cards/UserManagementCard.tsx

Fix UI display bug when user email is very long

---

app/src/main/frontend/views/GameView.tsx

Fix download providers not updating on view navigation event

---

app/src/main/frontend/components/administration/SsoManagement.tsx
app/src/main/kotlin/org/gameyfin/app/config/ConfigProperties.kt
app/src/main/kotlin/org/gameyfin/app/core/security/SecurityConfig.kt
app/src/main/kotlin/org/gameyfin/app/users/RoleService.kt

Make OAuth request scopes configurable & request OAuth scope "roles" by default 

---

app/src/main/frontend/views/GameRequestView.tsx
app/src/main/frontend/views/SearchView.tsx

Implement sorting for search page

---

app/src/main/kotlin/org/gameyfin/app/requests/GameRequestService.kt

Fix check of request limit of limit is set to 0 (unlimited)

---

app/src/main/frontend/views/SetupView.tsx

Handle error case in setup

---

app/src/main/resources/db/migration/V2.1.1__Recreate_game_image_fks_without_unique_indexes.sql

Recreate foreign key constraints for game cover and header images in DB
